---
- name: Update web servers
  hosts: webservers
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
  - name: Ensure wireshark is at the latest version
    apt:
      name: wireshark
      state: latest